services:
  - type: web
    name: nebulai-backend
    env: node
    plan: free
    buildCommand: npm install --prefix server
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: AI_PORT
        value: 5001
      - key: SECONDARY_AI_PORT
        value: 5002
      - key: DATABASE_URL
        fromDatabase:
          name: nebulai-db
          property: connectionString

  - type: web
    name: nebulai-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist

databases:
  - name: nebulai-db
    plan: free